version: "3"
services:
  react-app:
    image: node:18-alpine
    volumes:
      - .:/opt
    ports:
      - "5173:5173"
    command: npm run start
    networks:
      - travelAssistant-network
  api-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    env_file:
      - path: ./.env
    command: nodemon /opt/src/backend/app.js
    volumes:
      - .:/opt
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - travelAssistant-network
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27018:27017"
    volumes:
      - travelAssistantDB:/data/db
    networks:
      - travelAssistant-network
networks:
  travelAssistant-network:
    driver: bridge
volumes:
  travelAssistantDB:
    driver: local